function Background() {
    return (
        <div className="w-screen h-full relative font-monospace">
            <div className="absolute left-[6%] bottom-20 flex flex-col [&_span]:text-xs [&_span]:font-bold [&_span]:text-(--text-matrix) [&_span]:opacity-20 select-none">
                <span>D</span>
                <span>I</span>
                <span>S</span>
                <span>C</span>
                <span>I</span>
                <span>P</span>
                <span>L</span>
                <span>I</span>
                <span>N</span>
                <span>E</span>
                <span>-</span>
                <span>T</span>
                <span>O</span>
                <span>D</span>
                <span>A</span>
                <span>Y</span>
                <span>-</span>
                <span>F</span>
                <span>R</span>
                <span>E</span>
                <span>E</span>
                <span>D</span>
                <span>O</span>
                <span>M</span>
                <span>-</span>
                <span>T</span>
                <span>O</span>
                <span>M</span>
                <span>O</span>
                <span>R</span>
                <span>R</span>
                <span>O</span>
                <span>W</span>
            </div>
            <div className="absolute left-[18%] top-20 flex flex-col [&_span]:text-xs [&_span]:font-bold [&_span]:text-(--text-matrix) [&_span]:opacity-20 select-none">
                <span>C</span>
                <span>O</span>
                <span>D</span>
                <span>E</span>
                <span>-</span>
                <span>L</span>
                <span>E</span>
                <span>A</span>
                <span>R</span>
                <span>N</span>
                <span>-</span>
                <span>B</span>
                <span>U</span>
                <span>I</span>
                <span>L</span>
                <span>D</span>
                <span>-</span>
                <span>R</span>
                <span>E</span>
                <span>P</span>
                <span>E</span>
                <span>A</span>
                <span>T</span>
            </div>
            <div className="absolute left-[52%] top-40 flex flex-col [&_span]:text-xs [&_span]:font-bold [&_span]:text-(--text-matrix) [&_span]:opacity-20 select-none">
                <span>Q</span>
                <span>U</span>
                <span>I</span>
                <span>E</span>
                <span>T</span>
                <span>-</span>
                <span>B</span>
                <span>U</span>
                <span>T</span>
                <span>-</span>
                <span>N</span>
                <span>E</span>
                <span>V</span>
                <span>E</span>
                <span>R</span>
                <span>-</span>
                <span>S</span>
                <span>T</span>
                <span>I</span>
                <span>L</span>
                <span>L</span>
            </div>
            <div className="absolute right-[6%] bottom-20 flex flex-col [&_span]:text-xs [&_span]:font-bold [&_span]:text-(--text-matrix) [&_span]:opacity-20 select-none">
                <span>M</span>
                <span>A</span>
                <span>K</span>
                <span>E</span>
                <span>-</span>
                <span>P</span>
                <span>R</span>
                <span>O</span>
                <span>G</span>
                <span>R</span>
                <span>E</span>
                <span>S</span>
                <span>S</span>
                <span>-</span>
                <span>N</span>
                <span>O</span>
                <span>T</span>
                <span>-</span>
                <span>E</span>
                <span>X</span>
                <span>C</span>
                <span>U</span>
                <span>S</span>
                <span>E</span>
                <span>S</span>
            </div>
            <div className="absolute right-[19%] top-20 flex flex-col [&_span]:text-xs [&_span]:font-bold [&_span]:text-(--text-matrix) [&_span]:opacity-20 select-none">
                <span>R</span>
                <span>E</span>
                <span>M</span>
                <span>E</span>
                <span>M</span>
                <span>B</span>
                <span>E</span>
                <span>R</span>
                <span>-</span>
                <span>W</span>
                <span>H</span>
                <span>Y</span>
                <span>-</span>
                <span>Y</span>
                <span>O</span>
                <span>U</span>
                <span>-</span>
                <span>S</span>
                <span>T</span>
                <span>A</span>
                <span>R</span>
                <span>T</span>
                <span>E</span>
                <span>D</span>
            </div>
        </div>
    );
}

export default Background;
